Template.afCheckboxGroupInline_groupGrid.inheritsHelpersFrom("afCheckboxGroupInline")
Template.afCheckboxGroupInline_groupGrid.inheritsEventsFrom("afCheckboxGroupInline")
AutoForm.setDefaultTemplateForType('afCheckboxGroupInline', 'groupGrid')
